package gemini

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
)

type GeminiClient struct {
	APIKey string
	Model  string
}

func NewClient(apiKey string) *GeminiClient {
	if apiKey == "" {
		apiKey = os.Getenv("GEMINI_API_KEY")
	}
	return &GeminiClient{
		APIKey: apiKey,
		Model:  "gemini-flash-latest",
	}
}

type Content struct {
	Parts []Part `json:"parts"`
}

type Part struct {
	Text string `json:"text"`
}

type GenerateContentRequest struct {
	Contents []Content `json:"contents"`
}

type GenerateContentResponse struct {
	Candidates []Candidate `json:"candidates"`
}

type Candidate struct {
	Content Content `json:"content"`
}

type Sentence struct {
	En string `json:"en"`
	Es string `json:"es"`
}

func (c *GeminiClient) SplitStory(storyContent string) ([]Sentence, error) {
	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/%s:generateContent?key=%s", c.Model, c.APIKey)

	prompt := fmt.Sprintf(`Split the following story into short, meaningful sentences for English learners. For each sentence, provide the English version and its Spanish translation. 
Format the output STRICTLY as a JSON array of objects, each with "en" and "es" fields. 
Do not include any other text or formatting.

Story:
%s`, storyContent)

	reqBody := GenerateContentRequest{
		Contents: []Content{
			{
				Parts: []Part{
					{Text: prompt},
				},
			},
		},
	}

	jsonBody, err := json.Marshal(reqBody)
	if err != nil {
		return nil, err
	}

	resp, err := http.Post(url, "application/json", bytes.NewBuffer(jsonBody))
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		var errResp interface{}
		json.NewDecoder(resp.Body).Decode(&errResp)
		return nil, fmt.Errorf("gemini api error (status %d): %v", resp.StatusCode, errResp)
	}

	var res GenerateContentResponse
	if err := json.NewDecoder(resp.Body).Decode(&res); err != nil {
		return nil, err
	}

	if len(res.Candidates) == 0 || len(res.Candidates[0].Content.Parts) == 0 {
		return nil, fmt.Errorf("no content generated by gemini")
	}

	text := res.Candidates[0].Content.Parts[0].Text
	
	// Try to extract JSON if there's markdown around it
	start := bytes.Index( []byte(text), []byte("[") )
	end := bytes.LastIndex( []byte(text), []byte("]") )
	if start != -1 && end != -1 && end > start {
		text = text[start : end+1]
	}

	var sentences []Sentence
	if err := json.Unmarshal([]byte(text), &sentences); err != nil {
		return nil, fmt.Errorf("failed to parse gemini output: %v\nOutput: %s", err, text)
	}

	return sentences, nil
}
